export const INCREMENT = 'INCREMENT';
export const DECREASE = 'DECREASE';
export const INCREMENT_FIVE = 'INCREMENT_FIVE';
export const DECREASE_FIVE = 'DECREASE_FIVE';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';
